/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClaimAppealResponse } from '../../models/claim-appeal-response';
import { SubmitClaimAppealRequest } from '../../models/submit-claim-appeal-request';

export interface ClaimAppealSubmitClaimAppeal$Params {
  
    /**
     * The claim appeal request with invoice appeals
     */
    body: SubmitClaimAppealRequest
}

export function claimAppealSubmitClaimAppeal(http: HttpClient, rootUrl: string, params: ClaimAppealSubmitClaimAppeal$Params, context?: HttpContext): Observable<StrictHttpResponse<ClaimAppealResponse>> {
  const rb = new RequestBuilder(rootUrl, claimAppealSubmitClaimAppeal.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClaimAppealResponse>;
    })
  );
}

claimAppealSubmitClaimAppeal.PATH = '/api/claimappeals/submit';
