/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceAppealRequest {
  appealAdjustment?: number | null;
  appealReason: string;
  invoiceId: string;
}
