/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvoiceAppealRequest } from '../models/invoice-appeal-request';

/**
 * Request model for submitting claim appeals
 */
export interface SubmitClaimAppealRequest {
  claimId: string;
  selectedInvoices: Array<InvoiceAppealRequest>;
}
