/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { claimAppealGetClaimAppeal } from '../fn/claim-appeal/claim-appeal-get-claim-appeal';
import { ClaimAppealGetClaimAppeal$Params } from '../fn/claim-appeal/claim-appeal-get-claim-appeal';
import { claimAppealGetClaimAppealsByClaim } from '../fn/claim-appeal/claim-appeal-get-claim-appeals-by-claim';
import { ClaimAppealGetClaimAppealsByClaim$Params } from '../fn/claim-appeal/claim-appeal-get-claim-appeals-by-claim';
import { ClaimAppealResponse } from '../models/claim-appeal-response';
import { claimAppealSubmitClaimAppeal } from '../fn/claim-appeal/claim-appeal-submit-claim-appeal';
import { ClaimAppealSubmitClaimAppeal$Params } from '../fn/claim-appeal/claim-appeal-submit-claim-appeal';

@Injectable({ providedIn: 'root' })
export class ClaimAppealService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `claimAppealSubmitClaimAppeal()` */
  static readonly ClaimAppealSubmitClaimAppealPath = '/api/claimappeals/submit';

  /**
   * Submit a claim appeal with invoice details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `claimAppealSubmitClaimAppeal()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  claimAppealSubmitClaimAppeal$Response(params: ClaimAppealSubmitClaimAppeal$Params, context?: HttpContext): Observable<StrictHttpResponse<ClaimAppealResponse>> {
    return claimAppealSubmitClaimAppeal(this.http, this.rootUrl, params, context);
  }

  /**
   * Submit a claim appeal with invoice details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `claimAppealSubmitClaimAppeal$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  claimAppealSubmitClaimAppeal(params: ClaimAppealSubmitClaimAppeal$Params, context?: HttpContext): Observable<ClaimAppealResponse> {
    return this.claimAppealSubmitClaimAppeal$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClaimAppealResponse>): ClaimAppealResponse => r.body)
    );
  }

  /** Path part for operation `claimAppealGetClaimAppeal()` */
  static readonly ClaimAppealGetClaimAppealPath = '/api/claimappeals/{id}';

  /**
   * Retrieve a claim appeal by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `claimAppealGetClaimAppeal()` instead.
   *
   * This method doesn't expect any request body.
   */
  claimAppealGetClaimAppeal$Response(params: ClaimAppealGetClaimAppeal$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return claimAppealGetClaimAppeal(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieve a claim appeal by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `claimAppealGetClaimAppeal$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  claimAppealGetClaimAppeal(params: ClaimAppealGetClaimAppeal$Params, context?: HttpContext): Observable<void> {
    return this.claimAppealGetClaimAppeal$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `claimAppealGetClaimAppealsByClaim()` */
  static readonly ClaimAppealGetClaimAppealsByClaimPath = '/api/claimappeals/byclaim/{claimId}';

  /**
   * Get claim appeals for a specific claim.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `claimAppealGetClaimAppealsByClaim()` instead.
   *
   * This method doesn't expect any request body.
   */
  claimAppealGetClaimAppealsByClaim$Response(params: ClaimAppealGetClaimAppealsByClaim$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return claimAppealGetClaimAppealsByClaim(this.http, this.rootUrl, params, context);
  }

  /**
   * Get claim appeals for a specific claim.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `claimAppealGetClaimAppealsByClaim$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  claimAppealGetClaimAppealsByClaim(params: ClaimAppealGetClaimAppealsByClaim$Params, context?: HttpContext): Observable<void> {
    return this.claimAppealGetClaimAppealsByClaim$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
